DELETE FROM telefone;
DELETE FROM endereco;
DELETE FROM pessoa;

ALTER TABLE telefone ALTER COLUMN id RESTART WITH 1;
ALTER TABLE endereco ALTER COLUMN id RESTART WITH 1;
ALTER TABLE pessoa ALTER COLUMN id RESTART WITH 1;
