CREATE TABLE telefone (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ddd VARCHAR(2) NOT NULL,
  numero VARCHAR(9) NOT NULL,
  id_pessoa BIGINT NOT NULL,
  FOREIGN KEY (id_pessoa) REFERENCES pessoa(id)
);