CREATE SEQUENCE endereco_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE pessoa (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE endereco_id_seq PRIMARY KEY,
  logradouro VARCHAR(255),
  numero INT,
  complemento VARCHAR(255),
  bairro VARCHAR(255),
  cidade VARCHAR(255),
  estado VARCHAR(2),
  id_pessoa BIGINT NOT NULL,
  FOREIGN KEY (id_pessoa) REFERENCES pessoa(id)
);